server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/identity_service"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "eEA7TL6alwHClDCvMDsYKaZyqS5ElqjVaYsFZ9x2e5JLqGHdX1K+PV6Yc3aAzM6O"